import { ICourse } from "src/interfaces/ResponseInterface";

// TODO: someone fill this in pls
export const mockCourses: ICourse[] = [
  {
    courseCode: "COMP1511",
    archived: false,
    attributes: ["yeet"],
    calendar: "cal-123",
    campus: "Kensington",
    description: "rip chee",
    enrolmentRules: "idk",
    equivalents: ["COMP1911"],
    exclusions: ["COMP1010"],
    faculty: "Engineering",
    fieldOfEducation: "ugrad",
    genEd: true,
    level: 1,
    school: "CSE",
    studyLevel: "ugrad",
    terms: [0, 1, 2, 3],
    title: "good course imo",
    uoc: 6,
    rating: 4,
  },
  {
    courseCode: "COMP1531",
    archived: false,
    attributes: ["yeet"],
    calendar: "cal-123",
    campus: "Kensington",
    description: "hayden good",
    enrolmentRules: "idk",
    equivalents: ["COMP1911"],
    exclusions: ["COMP1010"],
    faculty: "Engineering",
    fieldOfEducation: "ugrad",
    genEd: true,
    level: 1,
    school: "CSE",
    studyLevel: "ugrad",
    terms: [2, 3],
    title: "good course imo",
    uoc: 6,
    rating: 4,
  },
];
